<?php

return array(

    'Algeria'                            => 18,
    'Austria'                            => 16,
    'Azerbaijan'                         => 18,
    'Bangladesh'                         => -1,
    'Belgium'                            => 16,
    'Botswana'                           => 18,
    'Brunei'                             => -1,
    'Burundi'                            => 16,
    'Canada (Ontario)'                   => 19,
    'Canada (Prince Edward Island)'      => 19,
    'Canada (Saskatchewan)'              => 19,
    'Cambodia'                           => 0,
    'Comoros'                            => 0,
    'Cyprus'                             => 17,
    'Fiji'                               => -1,
    'Germany'                            => 16,
    'Guam'                               => -1,
    'Guinea-Bissau'                      => 0,
    'Iceland'                            => 21,
    'India'                              => 25,
    'Jamaica'                            => 16,
    'Lesotho'                            => 18,
    'Libya'                              => -1,
    'Luxembourg'                         => 16,
    'Malta'                              => 17,
    'Micronesia'                         => 21,
    'Morocco'                            => 0,
    'Namibia'                            => 18,
    'New Zealand'                        => 18,
    'Norway'                             => 18,
    'Pakistan'                           => -1,
    'Palau'                              => 21,
    'Paraguay'                           => 20,
    'Qatar'                              => -1,
    'Samoa'                              => 21,
    'Sierra Leone'                       => 0,
    'Singapore'                          => 18,
    'Solomon Islands'                    => 21,
    'Sri Lanka'                          => 21,
    'Swaziland'                          => 18,
    'Tonga'                              => 21,
    'United Arab Emirates'               => -1,
    'United States'                      => 21,
    'Uzbekistan'                         => 0,
    'Vietnam'                            => 0,
    'Yemen'                              => -1,
    'Zambia'                             => 18,

);
